version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Gu20ru03
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: Guru
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: Guru
      SPRING_DATASOURCE_PASSWORD: rootpassword

  react-app:
        build: C:\Users\gguru\React\DockerReact\docker-demo
        container_name: react-frontend
        ports:
          - "3000:3000"
        depends_on:
          - springboot-app

volumes:
  mysql-data:
